### ISSUE TITLE
Problem: Celery worker not working

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/dip-access-interface#127]
In recent installations the Celery worker crashes with the following error:

```
[2019-03-13 12:25:36,423: CRITICAL/MainProcess] Unrecoverable error: VersionMismatch('Redis transport requires redis-py versions 3.2.0 or later. You have 2.10.6',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 921, in create_channel
    return self._avail_channels.pop()
IndexError: pop from empty list
 
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/usr/local/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.6/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/connection.py", line 23, in start
    c.connection = c.connect()
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 404, in connect
    conn = self.connection_for_read(heartbeat=self.amqheartbeat)
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 411, in connection_for_read
    self.app.connection_for_read(heartbeat=heartbeat))
  File "/usr/local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 435, in ensure_connected
    callback=maybe_shutdown,
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 422, in ensure_connection
    callback, timeout=timeout)
  File "/usr/local/lib/python3.6/site-packages/kombu/utils/functional.py", line 341, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 275, in connect
    return self.connection
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 823, in connection
    self._connection = self._establish_connection()
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 778, in _establish_connection
    conn = self.transport.establish_connection()
  File "/usr/local/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 941, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/usr/local/lib/python3.6/site-packages/kombu/transport/virtual/base.py", line 923, in create_channel
    channel = self.Channel(connection)
  File "/usr/local/lib/python3.6/site-packages/kombu/transport/redis.py", line 495, in __init__
    self.Client = self._get_client()
  File "/usr/local/lib/python3.6/site-packages/kombu/transport/redis.py", line 956, in _get_client
    'You have {0.__version__}'.format(redis))
kombu.exceptions.VersionMismatch: Redis transport requires redis-py versions 3.2.0 or later. You have 2.10.6
```

More info:

- https://github.com/celery/celery/issues/5369
- https://github.com/celery/kombu/issues/1016
- https://github.com/celery/kombu/issues/1019
- https://github.com/celery/kombu/issues/1018

Proposed solution is to pin `kombu==4.3.0` until Celery 4.3 gets released.

**Comment by cole** [comment]
Ugh, that is annoying. Too bad they're not using semver properly. Proposed solution sounds good, I think it's just important to remember to update kombu when you update celery in future.

**Comment by jraddaoui** [comment]
Thanks @cole. Unfortunately, pinning kombu didn't solve the issue. We also have redis-py pinned to 2.10.6 and it seems to be some important fixes in 3.2.0. How would you feel about upgrading redis-py and use `celery==4.3.0rc2` for the time being?

**Comment by jraddaoui** [comment]
Just tried with that and it looks like I'm having some issues building the Docker container as I'm getting the same issue. I'll try with the kombu pinning again to see if I'm able to properly re-build the container with the new deps.

**Comment by cole** [comment]
@jraddaoui I haven't tested the kombu pinning — just saw that it is working for others in the linked issues and it sounds ok in principle. Maybe try pinning kombu and updating redis? It seems that 4.3 requires redis 3.2+

**Comment by jraddaoui** [comment]
Okay, I got it working with both setups. I'll pin kombu until celery 4.3 is released. As @cole mentions we'll need to upgrade or remove the kombu dependency when we upgrade celery and also upgrade redis to 3.2.0 or higher.

**Comment by jraddaoui** [comment]
> @jraddaoui I haven't tested the kombu pinning — just saw that it is working for others in the linked issues and it sounds ok in principle. Maybe try pinning kombu and updating redis? It seems that 4.3 requires redis 3.2+

Sorry @cole, I missed that update.

kombu 4.4 requires redis 3.2, but they don't work well with celery 4.2 and celery 4.3 is still a RC. Pinning kombu to 4.3 works in the end (it was a Docker issue on my end) and I think it's the best option until celery 4.3 is released.

**Comment by cole** [comment]
Sounds good!

**Comment by jraddaoui** [comment]
Thanks @cole!

**Comment by sallain** [comment]
@stefanabreitwieser If DIP upload and descendant updates work, this can be closed.

**Comment by jraddaoui** [comment]
Sorry, the application has not been updated in the test server, I'll mark this for review once the search filters pull request is merged and deployed, which will also include the fix for this issue.

**Comment by jraddaoui** [comment]
This is now ready for review in the test instance.

**Comment by jraddaoui** [comment]
The worker crashed again with the following error:

```
[2019-03-20 05:51:45,476: CRITICAL/MainProcess] Unrecoverable error: ResponseError('MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.',)
Traceback (most recent call last):
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/kombu/transport/redis.py", line 1065, in on_readable
    self.cycle.on_readable(fileno)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/kombu/transport/redis.py", line 348, in on_readable
    chan.handlers[type]()
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/kombu/transport/redis.py", line 725, in _brpop_read
    **options)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
```

From the Redis service logs:
```

**Comment by jraddaoui** [comment]
Only Elasticsearch is currently taking 1.3 GB of memory from the 2 GB available in that instance:

```
root@scope:~# systemctl status elasticsearch
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-03-19 20:35:45 UTC; 24h ago
     Docs: http://www.elastic.co
 Main PID: 1443 (java)
    Tasks: 54
   Memory: 1.3G
      CPU: 12min 26.116s
   CGroup: /system.slice/elasticsearch.service
           ├─1443 /usr/bin/java -Xms1g -Xmx1g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -Xss1m -Djava.a
           └─1835 /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller
``` 
Which doesn't leave a lot of space to parse big METS files at this time.

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser and @bunekcca,

I guess you noted the same issue again about a couple of hours ago. I forgot that we're also running Kibana in there which, alongside Elasticsearch, were taking almost all the memory in the server, so I've increased it from 2 to 4 GB. Please, let me know how it goes.

**Comment by stefanabreitwieser** [comment]
It's working a lot faster -- thanks Radda!
