### ISSUE TITLE
Problem: Error occurred during the process executed to extract and parse the METS file

### ISSUE THREAD

**Issue by stefanabreitwieser** [CCA-Public/dip-access-interface#129]
We've been getting the following error with a handful of our DIPs: 

```
Traceback (most recent call last):
  File "/opt/dip-access-interface/dips/parsemets.py", line 108, in parse_mets
    digitalfile.full_clean()
  File "/opt/dip-access-interface/venv/lib/python3.6/site-packages/django/db/models/base.py", line 1152, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'puid': ['Ensure this value has at most 11 characters (it has 19).']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/dip-access-interface/venv/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/dip-access-interface/venv/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/dip-access-interface/venv/lib/python3.6/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/dip-access-interface/dips/tasks.py", line 71, in extract_and_parse_mets
    mets.parse_mets()
  File "/opt/dip-access-interface/dips/parsemets.py", line 113, in parse_mets
    raise METSError(message)
dips.parsemets.METSError: A DigitalFile could not be created:
- puid: Ensure this value has at most 11 characters (it has 19).
```

We assumed initially this was related to our compressed AIP issues, but these DIPs shouldn't be affected by that. I'm still able to download the zip file, but it doesn't grab any of the data from the METS file to populate the "Digital files in this folder" section of the Folder. Thanks!

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser, the `puid` field has always been limited to 11 chars:

https://github.com/CCA-Public/dip-access-interface/blob/master/dips/models.py#L380

@sallain, would you know how long can this field be? It's obtained from the following path within each file's AMD section:

https://github.com/CCA-Public/dip-access-interface/blob/master/dips/parsemets.py#L31

**Comment by sallain** [comment]
`formatRegistryKey` is part of the object's file format identification information - it refers to the PRONOM identifier for the format:

```
<premis:formatRegistry>
   <premis:formatRegistryName>PRONOM</premis:formatRegistryName>
   <premis:formatRegistryKey>fmt/101</premis:formatRegistryKey>
</premis:formatRegistry>
```

The above example, `fmt/101`, is pretty standard - usually it's the prefix `fmt` or `x-fmt`, a slash, then the identifier number. PRONOM IDs are up into the 4-digit range now.

However, there are exceptions, which occur when a format was added directly to Archivematica rather than pulled in from PRONOM. Here's a random example that I found by looking at the list of formats in Archivematica's Preservation Planning tab.

![image](https://user-images.githubusercontent.com/4612276/54395029-d45fbd80-466b-11e9-9fe9-03b4cb9e8ed8.png)

You can see that the puid for certain kinds of AD1 disks is longer than 11 characters. These examples are definitely rare but they do happen, so it probably makes sense to set that character limit higher.

@stefanabreitwieser out of curiosity, do you know which formats were in the DIP you tried to upload? And good catch!

**Comment by stefanabreitwieser** [comment]
@sallain I uploaded two! The first had WordPerfect for MS-DOS/Windows Document (v. 5.1), The other had Microsoft Word for Macintosh Document (v. 5.0). Both very long file format names!

This is something that's definitely a priority to be fixed. @jraddaoui you have the go-ahead on this whenever you have the time -- thanks!

**Comment by sallain** [comment]
@stefanabreitwieser Ohhh interesting... I wanted to check the PRONOM IDs for those two formats, but found out that AM doesn't know about WordPerfect for MS-DOS/Windows Document (v. 5.1), only v.6. So I think the fallback is probably to use the file format name which is, as you note, quite long. If you have a chance I'd love to see the METS file to confirm this!

**Comment by stefanabreitwieser** [comment]
Attached!
[METS.87a40b5a-b9bf-4847-a9a3-a19fa822fa9e.zip](https://github.com/CCA-Public/dip-access-interface/files/2972660/METS.87a40b5a-b9bf-4847-a9a3-a19fa822fa9e.zip)
[METS.0b29884a-85f3-44dd-a77b-60c0d37f3433.zip](https://github.com/CCA-Public/dip-access-interface/files/2972662/METS.0b29884a-85f3-44dd-a77b-60c0d37f3433.zip)

**Comment by sallain** [comment]
Interesting - those METS files don't contain the `premis:formatRegistryKey` field at all, so I'm not actually sure where the PUID value could be coming from. Anyway, I'm sure that Radda will investigate more thoroughly as he works on a fix :)

**Comment by jraddaoui** [comment]
I can't see the `formatRegistry` information in those METS files either, but I have increased the `puid` field length limit to 200 chars in the related pull request, the same as the `fileformat` and `formatversion` fields for the `DigitalFile` model. I hope that's enough.

**Comment by jraddaoui** [comment]
Hi @sallain, this is ready for review in the test instance.

**Comment by stefanabreitwieser** [comment]
@jraddaoui I just tried to re-add one of the problem DIPs and now I'm getting the following error message: 

> Traceback (most recent call last):
>   File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/celery/app/trace.py", line 382, in trace_task
>     R = retval = fun(*args, **kwargs)
>   File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/celery/app/trace.py", line 641, in __protected_call__
>     return self.run(*args, **kwargs)
>   File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/celery/app/base.py", line 467, in run
>     return task._orig_run(*args, **kwargs)
>   File "/home/scope/dip-access-interface/dips/tasks.py", line 69, in extract_and_parse_mets
>     mets.parse_mets()
>   File "/home/scope/dip-access-interface/dips/parsemets.py", line 128, in parse_mets
>     if premisevent.digitalfile.id != digitalfile.id:
> AttributeError: 'DigitalFile' object has no attribute 'id'
> 

METS file is attached -- hope that helps! Thanks!
[METS.b2283818-6be2-4744-bf5c-d252fb967470.zip](https://github.com/CCA-Public/dip-access-interface/files/2993442/METS.b2283818-6be2-4744-bf5c-d252fb967470.zip)

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser, 

That issue should be fixed in the test instance. However, if you delete the DIP and retry the upload, you may see "A PREMISEvent in this METS file has the same UUID as an existing one from another DIP" error. If you see that, it may be some data from the old DIP in the database and I wonder if you would be able to delete it through the interface or if we'll have to do it directly in the DB.

Please, let me know how it goes.

**Comment by stefanabreitwieser** [comment]
Hi @jraddaoui 

I deleted and re-uploaded the SIP and now have a new error (unrelated to the repeated UUID). The SIP is ARCH279622 under the Anyone collection. 

```
An error occurred during the process executed to extract and parse the METS file. Error trace:
Traceback (most recent call last):
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: dips_dublincore.source

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/celery/app/base.py", line 476, in run
    raise task.retry(exc=exc, **retry_kwargs)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/celery/app/task.py", line 667, in retry
    raise_with_context(exc)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/celery/app/base.py", line 467, in run
    return task._orig_run(*args, **kwargs)
  File "/home/scope/dip-access-interface/dips/tasks.py", line 69, in extract_and_parse_mets
    mets.parse_mets()
  File "/home/scope/dip-access-interface/dips/parsemets.py", line 162, in parse_mets
    dip.dc.save()
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/django/db/models/base.py", line 812, in _save_table
    forced_update)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/django/db/models/base.py", line 861, in _do_update
    return filtered._update(values) > 0
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/django/db/models/query.py", line 712, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1383, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/scope/dip-access-interface/venv/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 298, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: dips_dublincore.source
```

I have no idea why these SIPs in particular are throwing so many errors, but if you have any thoughts, please let me know! Thank you!

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser, it looks like this DIP is hitting part of the import and METS parsing code that has not been reached in a long time, which is great at this point.

In this case, it seems like the `source` element is missing in the DIP Dublin Core metadata from the METS file and this field can't be `NULL` in the database. It shouldn't be hard to fix.

**Comment by jraddaoui** [comment]
Ok, fixes merged and deployed in the test instance, I hope this time is the good one.

Sorry for all the troubles @stefanabreitwieser.

**Comment by stefanabreitwieser** [comment]
It works!! Thanks Radda :)
