### ISSUE TITLE
Error in login page

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/dip-access-interface#21]
The first time entering the GUI, after the admin user is created in the CLI, yo are redirected to the login page, with the following error:

```
Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 315, in render
    match = condition.eval(context)
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/template/defaulttags.py", line 892, in eval
    return self.value.resolve(context, ignore_failures=True)
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/template/base.py", line 736, in resolve
    new_obj = func(obj, *arg_vals)
  File "/home/radda/dip-access-interface/accesspoc/dips/templatetags/custom_tags.py", line 12, in has_group
    group = Group.objects.get(name=group_name)
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/radda/dip-access-interface/venv/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: Group matching query does not exist.
```

**Comment by jraddaoui** [comment]
By creating the user group in the migration process, this issue no longer happens.
